### ISSUE TITLE
Feature: add icons on menu and app

### ISSUE THREAD

**Issue by Macleykun** [lucaIz-ldx/MobileTSS#3]
First, i love using your TSS saver! It saved my future restore to 12.4 (from 12.0.1 A12)! I use yours aswell next to tsssaver!

I noticed your app looks nice, but could use a little bit of icons, i asked the_castle how he got his icons and he uses this:
https://ko.icons8.com/ios

It's free/opensource and they look really neat (imo). Maybe you like to use these aswell?

Thank you for making such a great app! Can't wait to see a .deb version and possibly saving beta firmware aswell!

**Comment by Macleykun** [comment]
@lucaIz-ldx any comment on this? You intrested to add these?

**Comment by lucaIz-ldx** [comment]
Yes I will. Since this is not a critical issue, I tend to delay it and I will do it when I am free. Thanks for suggestion.

**Comment by Macleykun** [comment]
No problem! Glad to hear your considering it! Thanks for the great app!

Van: lucaIz-ldx
Verzonden: vrijdag 1 november 2019 12:54
Aan: lucaIz-ldx/MobileTSS
CC: Macley; Author
Onderwerp: Re: [lucaIz-ldx/MobileTSS] Icons!? (#3)

Yes I will. Since this is not a critical issue, I tend to delay it and I will do it when I am free. Thanks for suggestion.

**Comment by lucaIz-ldx** [comment]
> Thank you for making such a great app! Can't wait to see a .deb version and possibly saving beta firmware aswell!

By the way, you already can save beta blobs now. Ipsw.me only provides OTA beta URLs and version numbers for those are weird (unlike what we see in public firmware version). The only way to do it for now is to enter URL for beta firmwares (from the iPhone Wiki) manually in "Custom" page (you can drag and drop URL if the device supports). I will come up a better solution if possible.

**Comment by Macleykun** [comment]
True! But beta's are more for the really rare times that i would have no option, then to go to that specific beta.
I'll stick to the URL way for now, i look forward to your next update! Thank you again!

**Comment by Macleykun** [comment]
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/system-icons/
Found some more icons :P

**Comment by lucaIz-ldx** [comment]
Thanks for that. I've already implemented most icons in 1.3 which should be released soon.

**Comment by Macleykun** [comment]
Nice! Can’t wait to see it! Thank you dude!

**Comment by Macleykun** [comment]
Heya dude, was wondering when a new release was comming up!
Is everything allright?

**Comment by Macleykun** [comment]
Heya, any update on this?

**Comment by Macleykun** [comment]
Hello, is still project still active?

**Comment by Macleykun** [comment]
@lucaIz-ldx any progress on this?

**Comment by lonkelle** [comment]
@Macleykun I didn't see this issue before I opened mine about the icon (https://github.com/lucaIz-ldx/MobileTSS/issues/6) - may I ask why you closed it? I still have a blank icon on my screen for MobileTSS in jailed mode (in jb mode I can just theme the icon).

**Comment by Macleykun** [comment]
Oh hey lonkle I think I’ve seen ya as one of the mods in the server!
I closed it bc I assumed the feature would never be implemented. As it’s not a very important thing I sometimes close issues like these if a project seems abdoned to me. But ya free to fork make your changes and make a pull (bonus points if ya make a release ;))

If you wish for me to reopen I’ll do so, but I wouldn’t count on this one being solved (and I respect that decision)

**Comment by lonkelle** [comment]
If @lucaIz-ldx **publicly** announces that MobileTSS is abandoned, I will fork it. I find this valuable to the jailbreak community to have automatic blobs saved on device designed *for* jailed devices.

I know there's more icons to implement as you described @Macleykun, but if you want just the app icon like I wanted. Two options I wanna outline to anyone that comes across this ticket:

• Jailed: Install / sideload app via AltStore. After installation, hold down on the app now listed in AltStore's "My Apps" page and hit change icon to make it any icon you want while jailed.
• Jailbroken: Use sn0wboard.

Oh, and @Macleykun - I recommend re-opening this issue since it was not resolved. It'll help me fork it later. Because marking a ticket resolved when it's not could cause confusion for future-forker and / or make people believe the app is stable / doesn't have issues. But, that's just my personal opinion on issue management on GitHub. 🙃

**Comment by Macleykun** [comment]
Ah i was actually refering to the internal icons more so. The external one is one i theme with snowboard haha.
Tbh i don't mind either way as i manually check tss saver and shsh.host :P. future restoring hasn't gone well for me most of the time so i'm not as interested as the others are (b/c of outdated docs, iphone had to update to newest 14.4 sadly).

About the owner, i think it's beter to assume it's abandoned and fork it, make changes and make a pull request, rather then waiting. I'll reopen the issue until a pull is made for what you want.

I'll revisit this issue in a couple months, and if the pull hasn't created/pulled in, i'll close and put a ref into that pull if not done so.

Technically if the user sees a closed issue and scrolls down and sees nothing resolved, they can assume it wasn't resolved/fixed.
App is technically stable with or withoud resolving this issue, it's more a nice to have rather then a fix :P. But i do get your point and that's indeed the way things should be. I just want to clear stuff up once in a while if it's inactive.

gl on the fork o/

**Comment by lonkelle** [comment]
@Macleykun That makes perfect sense. Thanks for re-opening it for me for now! ☺️

**Comment by lonkelle** [comment]
PS. When I make that fork, I might think about an Apple TV release as well. I like the concept of all blobs being saved on their respective devices and tvOS needs this too. Also maybe add unc0ver detection to auto-set the generator to unc0ver's default. Hmm, got a lot to think about. 😅

**Comment by Macleykun** [comment]
> PS. When I make that fork, I might think about an Apple TV release as well. I like the concept of all blobs being saved on their respective devices and tvOS needs this too. Also maybe add unc0ver detection to auto-set the generator to unc0ver's default. Hmm, got a lot to think about. 😅

fork it, and make on the readme/issues clear what you want to achieve.
I'm sure given your status in the community that multiple people can come in and help a hand if they/you want so. Just make sure to make a clear path and goal (i didn't with a project, doesn't feel good).
Don't forget to not prefer a certain jailbreak :P some like u0, some like the work of CS, and probably a few also like other types of ways to set the nonce etc.

Wish ya gl on it o/ (don't forget that you can use a internal app url so that users only have to click one link to open and download/install MobileTSS with altstore :) (and a warning that repro is dead would be wise aswell, ya be suprised how many people use it still)

**Comment by lucaIz-ldx** [comment]
Thanks for asking about the progress. Unfortunately, I have decided to suspend development of this application. We already have blobs saving tools on device like TSSSaver app and SystemInfo tweak. There is no point to maintain another tool for very few users. In fact, I never planned to implement saving & verifying blobs in this app when I created this project on day one. I added those features because someone suggested me to do so and I made promise on that. However, my original goal is to implement Haifisch's idea with tihmstar's tsschecker: it is just an app to see what firmwares are being signed, nothing else. I have reached the goal since this feature is not broken and should still work on future devices. 

I won't consider this project is abandoned as I will still push critical fixes if it fails to query signing status at some point in future (for example, Apple does some changes in TSS server), but no features will be added nor support for new devices. If you want to add them, feel free to open a pull request or just do them in your own fork.

All blobs saved for devices before iPad 10.2 and iPhone 11 are still valid and should be valid saved for future firmwares. You should not use it for saving blobs for any newer devices like iPhone 12; I do not guarantee they are usable for futurerestore (even if it reports the blob is valid) so use it at your own risk.

**Comment by lonkelle** [comment]
@lucaIz-ldx Understood. I do consider this to fill a niche that doesn't elsewhere exist – jailed-focused automatic blob saver on device. I have it on both my iPhone 12s....which means the blobs are probably incorrect. Dang. That's fine. How important could 14.4 be anyway. 😅 So, are you assuming the A13 and A14 are so different that an iPhone 11 would save correctly but an iPhone 12 wouldn't. 

I haven't come across any nonces changes in methodology past A12. I imagine they would still work. Have you just not testing them because I suppose I can do that now that 14.4 isn't being signed anymore. 

Would you like me to do that for you real quick so you can be certain if the iPhone 12 is an app MobileTSS supports?

**Comment by lucaIz-ldx** [comment]
I am not saying they are unusable. I cannot make guarantees I don't know. I did not assume there are differences among A12, A13 and A14 devices; I did not update code for tsschecker since then. You don't need to do that test. Even if blobs saved for A13+ are not valid, I will not push a dedicated fix.

**Comment by lonkelle** [comment]
But you’ll accept a pull request if I do this critical for new devices fix, correct?

Because if my blobs work then your application works for iPhone 12 and there’s no reason to hide that. But if I test and it needs a fix. I’ll do a PR.

**Comment by Macleykun** [comment]
Heya, any update on this one :P ?

**Comment by lonkelle** [comment]
@Macleykun Luca wants to keep maintaining MobileTSS so I have gone a different route and am building this directly into AltStore. So you can close this I'd say. 

https://trello.com/c/bHMWYUak

If I remember, I'll post back on this issue and let you know when I finish building my alternative solution (assuming you use AltStore ofc).

**Comment by Macleykun** [comment]
Perfect! Great work dude :)
