### ISSUE TITLE
Error when verifying saved blobs in-app on iPhone 12 mini (A12+ presumably)

### ISSUE THREAD

**Issue by lonkelle** [lucaIz-ldx/MobileTSS#4]
I can save blobs corrects via your app on my iPhone 12 mini  (I entered in the ECID, APNonce, and Generator all correctly, double checked) - and the blobs generated are considered valid if I use:

https://tsssaver.1conan.com/check/

Despite that when I try to verify the blobs that you save in app using your own built-in verification message, I get an error that it is missing certain things (attached). Just wondering why TSS Saver considers your generated blobs valid, but your own in app verifier doesn’t. Here iswhat your app says is missing in its log it shows me after the “verify” process. 

![3AB0BF5E-DC02-4FED-B911-A9464B8052AB](https://user-images.githubusercontent.com/5572600/111060935-e9e46980-8476-11eb-9af0-c56f1fbfc8dd.jpeg)

Can you reproduce this?

**Comment by lonkelle** [comment]
Note: I just used your app to save the blobs for my iPad mini 4 for 14.4 and it saved **and verified** perfectly. I only had to grab my ECID for that (copy and pasted it from unc0ver). 

I realize A12+ device require the custom generator (which I set correctly) and the APNonce that that generator generates (which I also set correctly) - but there is still something missing in your verification technique for those types of blobs. Because I verified my entered in generator and APNonce saved blobs and it was valid using the TSS checker but invalid using your own built in checker.

**Comment by lucaIz-ldx** [comment]
I spent some time comparing code latest tsschecker and there are nearly no changes so all blobs saved so far including new devices after 2020 are valid just like use current tsschecker. 
However, img4tool need to be updated every time when Apple releases new devices with new firmware components. I am considering to drop blobs verification since the purpose of this functionality is completely reversed: we have to accommodate new shsh2 files and make sure our verifier not report any error. For now, I just disabled it.

**Comment by lonkelle** [comment]
@lucaIz-ldx Nice! Thanks for looking into that for me. If you disable the checker since it doesn't work, but the blobs are still valid then there is no error here and I'm closing this issue. Awesome that you're still working on this! I think it's a great app.
